FROM node:alpine

RUN apk --no-cache add nodejs nginx

COPY devops/client.nginx.conf /etc/nginx/nginx.conf

WORKDIR /opt/YoYo/client

COPY client/package.json .
RUN npm install \
 && npm cache clean

COPY client .
RUN npm run build-prod

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
