FROM alpine:latest

RUN apk --no-cache add nginx nodejs

COPY devops/local/admin.nginx.conf /etc/nginx/nginx.conf

WORKDIR /opt/YoYo/admin

COPY admin/package.json .
RUN npm install \
 && npm cache clean

COPY admin .
RUN npm run build-prod

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
