service: YoYo

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage}
  region: us-east-1
  environment:
    YOYO_EMAIL: ${opt:YOYO_EMAIL}
    YOYO_DB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    SITE_OWNER_EMAIL: ${opt:SITE_OWNER_EMAIL}
    SENDGRID_API_KEY: ${opt:SENDGRID_API_KEY}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.YOYO_DB_TABLE}"

package:
  include:
    - handler.js
    - config.js

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: /comments
          method: post
          cors: true
  query:
    handler: handler.query
    events:
      - http:
          path: /comments
          method: get
          cors: true
  get:
    handler: handler.get
    events:
      - http:
          path: /comments/{id}
          method: get
          cors: true
  update:
    handler: handler.update
    events:
      - http:
          path: /comments/{id}
          method: put
          cors: true

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: ${self:provider.environment.YOYO_DB_TABLE}
